#!/usr/bin/env bash
# Install nginx web server
# nginx must be listening on port 80
# nginx must return a page that contains the string "Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
