#!/usr/bin/env bash
# Configures a server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently".

apt-get -y update
apt-get -y install nginx

echo "Hello World!" > /etc/nginx/html/index.html
sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
