#!/usr/bin/env bash
# Bash script that displays the content of the file school file
#   If the file does not exist, displays: School file does not exist
#   If the file exists, displays the content of the file

file="school"
if [ -e "$file" ]
then
	echo "school file exists"
	if [ -s "$file" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$file" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
